spring:
  application:
    name: keycloak-demo
  liquibase:
    change-log: classpath:db/changelog-master.xml
    default-schema:
    drop-first: false
    contexts: crdb
    enabled: true

  # datasource:
  #   url: jdbc:postgresql://localhost:26257/lottery_app_db?sslmode=verify-full&sslrootcert=src/main/certs/ca.crt
  #   driver-class-name: org.postgresql.Driver
  #   username: eyob
  #   password: eyob@1234
  #   hikari:
  #     connection-test-query: SELECT 1
  #     maximum-pool-size: 50
  #     minimum-idle: 20

  # jpa:
  #   open-in-view: false
  #   properties:
  #     hibernate:
  #       dialect: org.hibernate.dialect.PostgreSQLDialect
  #   show-sql: false
  #  datasource:
  #    url: jdbc:postgresql://localhost:5432/lottery-app-db
  #    username: keycloak_user
  #    password: keycloak@1234
  #    driver-class-name: org.postgresql.Driver
  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  #    show-sql: false
  #    properties:
  #      hibernate:
  #        format_sql: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://ep-white-leaf-66290301.us-east-2.aws.neon.tech/lottery_db_app
    username: eyobtadele2705
    password: AZGydo02WNlF

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}

  mail:
    host: smtp.gmail.com
    port: 587
    username:

    #app password
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 1811
  servlet:
    context-path: /auth

app:
  keycloak:
    admin:
      clientId: admin-cli
      clientSecret: baghc5OoQLEKS2087YIukeotDoPTdZsv
    realm: Addis Financial
    serverUrl: http://localhost:9082

application:
  mailing:
    activation-url: http://localhost:1810/
